language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
after_success:
  - bash ./travis/unit-test-success.sh
after_failure:
  - bash ./travis/unit-test-fail.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master